StoreLaptopApp/Models/StoreEntities/Comment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace StoreLaptopApp.Models.StoreEntities
{
    public class Comment
    {
        [Key]
        public int Id { get; set; }
        public string IdAccount { get; set; }
        public string NameAccount { get; set; }
        public string Content { get; set; }
        public int Note { get; set; }
        public DateTime Day { get; set; }


        [ForeignKey("Product")]
        public int ProductId { get; set; }
        public Product Product { get; set; }
    }
}

StoreLaptopApp/Controllers/CommentController.cs
using Microsoft.AspNet.Identity;
using StoreLaptopApp.Models.Bus;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StoreLaptopApp.Controllers
{
    public class CommentController : Controller
    {
        // GET: Comment
        public ActionResult Create(int masp, String Content, string IdAccount, string NameAccount)
        {
            CommentBus.ThemComment(masp, Content, User.Identity.GetUserId(), User.Identity.Name);
            return RedirectToAction("Details", "Product", new { Id = masp });
        }
        public ActionResult Index(int masp)
        {
            ViewBag.Id = masp;
            return View(CommentBus.DanhSach(masp));
        }
    }
}

StoreLaptopApp/Views/Comment/Index.cshtml
@model IEnumerable<DoAnChuyenNganhConnection.Comment>
@{
    ViewBag.Title = "Index";
    Layout = null;
}
<h2>Bình luận</h2>

@using (Html.BeginForm("Create", "Comment", FormMethod.Post))
{

    @Html.AntiForgeryToken()
    @Html.Hidden("masp", (int)ViewBag.Id)
    @*@Html.TextArea("Content")*@
    <textarea cols="100" id="Content" name="Content" rows="1"></textarea>
    <br />
    <input type="submit" value="Đăng" />

}
<div id="comments">
    @foreach (var item in Model)
    {
        <div class="comment">
            <div class="comment-name" style="font-weight: bold">@item.NameAccount</div>
            <div class="comment-content">@item.Content</div>
            <div class="comment-content">@item.Day</div>
        </div>
    }


</div>