StoreLaptopApp/Models/StoreEntities/OrderDetail.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace StoreLaptopApp.Models.StoreEntities
{
    public class OrderDetail
    {
        [Key]
        [Column(Order = 1)]
        public int OrderId { get; set; }
        [Key]
        [Column(Order = 2)]
        public int ProductId { get; set; }
        public double Price { get; set; }
        public int Quantity { get; set; }
        public double TotalPrice { get; set; }

        public Order Order { get; set; }
        public Product Product { get; set; }
    }
}

StoreLaptopApp/Controllers/OrderDetailsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StoreLaptopApp.Models;
using StoreLaptopApp.Models.StoreEntities;

namespace StoreLaptopApp.Controllers
{
    public class OrderDetailsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            List<OrderDetail> orderDetail = db.OrderDetails.Where(o => o.OrderId == id).Include(o => o.Product).ToList();
            if (orderDetail == null)
            {
                return HttpNotFound();
            }
            return View(orderDetail);
        }
    }
}

StoreLaptopApp/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using StoreLaptopApp.Models;
using StoreLaptopApp.Models.StoreEntities;

namespace StoreLaptopApp.Controllers
{
    public class OrdersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Orders
        public ActionResult Index()
        {
            string userid = User.Identity.GetUserId().ToString();
            var orders = db.Orders.Where(u => u.CustomerId == userid).Include(o => o.Customer).Include(o => o.Employees);
            return View(orders.ToList());
        }
    }
}

StoreLaptopApp/Views/OrderDetails/Details.cshtml
@model IEnumerable<StoreLaptopApp.Models.StoreEntities.OrderDetail>
@using System.Globalization;
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>OrderDetail</h4>
    <table class="table">
        <thead>
            <tr>
                <th>Product Name</th>
                <th>Image</th>
                <th>Price</th>
                <th>Quantity</th>
                <th>Sum</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(model => item.Product.Name)
                    </td>
                    <td>
                        <img src="@Url.Content(item.Product.Cover)" style="width: 100px; height: 100px;" />
                    </td>
                    <td>
                        @Html.DisplayFor(model => item.Product.Price)
                    </td>
                    <td>
                        @Html.DisplayFor(model => item.Quantity)
                    </td>
                    <td>
                        <h5>@string.Format(new CultureInfo("vi-VN"), "{0:#,##0}", item.Price)<span>VNĐ</span></h5>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
<p>
    <a href="@Url.Action("Index","Orders")">Back to list</a>
</p>