StoreLaptopApp/Areas/admin/Controllers/CommentAdminController.cs
using DoAnChuyenNganhConnection;
using StoreLaptopApp.Models.Bus;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StoreLaptopApp.Areas.admin.Controllers
{
    public class CommentAdminController : Controller
    {
        [Authorize(Roles = "Admin")]
        // GET: admin/CommentAdmin
        public ActionResult Index()
        {
            var ds = CommentBus.DanhSachAdmin();
            return View(ds);
        }

        // GET: admin/CommentAdmin/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: admin/CommentAdmin/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: admin/CommentAdmin/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: admin/CommentAdmin/Edit/5
        public ActionResult Edit(int id)
        {
            return View(CommentBus.ChiTiet(id));
        }

        // POST: admin/CommentAdmin/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Comment comment)
        {
            try
            {
                // TODO: Add update logic here
                CommentBus.UpdateAdmin(id, comment);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: admin/CommentAdmin/Delete/5
        public ActionResult Delete()
        {
            return View();
        }

        // POST: admin/CommentAdmin/Delete/5
        [HttpPost]
        public ActionResult Delete(FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

StoreLaptopApp/Areas/admin/Views/CommentAdmin/Edit.cshtml
@model DoAnChuyenNganhConnection.Comment
@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
}

<style>

    input[type=text] {
        width: 100%;
        padding: 12px 20px;
        margin: 8px 0;
        display: inline-block;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
    }

    input[type=submit] {
        width: 100%;
        background-color: #4CAF50;
        color: white;
        padding: 14px 20px;
        margin: 8px 0;
        border: none;
        border-radius: 4px;
        cursor: pointer;
    }

        input[type=submit]:hover {
            background-color: #45a049;
        }

    /*div {
        border-radius: 5px;
        background-color: #f2f2f2;

        margin: auto;
    }*/
</style>

<div style=" padding: 20px;">
    @using (Html.BeginForm("Edit", "CommentAdmin", FormMethod.Post, new
    {

    }))
    {

        <label for="fname">Mã </label>
        <input type="text" id="fname" name="Id" placeholder="" required value="@Model.Id">

        <label for="fname">Mã người dùng </label>
        <input type="text" id="fname" name="IdAccount" placeholder="" required value="@Model.IdAccount">

        <label for="fname">Tên người dùng </label>
        <input type="text" id="fname" name="NameAccount" placeholder="" required value="@Model.NameAccount">

        <label for="lname">Nội dung</label>
        <input type="text" id="lname" name="Content" placeholder="" required value="@Model.Content">

        <label for="lname">Sản phẩm</label>
        <input type="text" id="lname" name="ProductId" placeholder="" required value="@Model.ProductId">

        <label for="lname">Ngày giờ</label>
        <input type="text" id="lname" name="Day" placeholder="" required value="@Model.Day">



        <label for="country">Tình trạng</label>
        <select id="country" name="Note" style="width:89px;height:26px;" required value="@Model.Note">
            <option value="1">Duyet</option>
            <option value="0">Khong duyet</option>


        </select>

        <input type="submit" value="Submit">
    }
</div>

StoreLaptopApp/Areas/admin/Views/CommentAdmin/Index.cshtml
@model IEnumerable<DoAnChuyenNganhConnection.Comment>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
}

<style>
    table {
        border-collapse: collapse;
        width: 100%;
        margin: auto;
    }

    th, td {
        text-align: center;
        padding: 8px;
    }

    tr:nth-child(even) {
        background-color: #f2f2f2
    }

    th {
        background-color: #04AA6D;
        color: white;
    }
</style>



<table>
    <tr>
        <th>Mã</th>
        <th>Mã người dùng</th>
        <th>Tên người dùng</th>
        <th>Nội dung</th>
        <th>Thời gian</th>
        <th>Mã sản phẩm</th>
        <th>Duyệt</th>
        <th colspan="2">

        </th>

    </tr>
    @foreach (var item in Model)
    {

        <tr>
            <td>@item.Id</td>
            <td>@item.IdAccount</td>
            <td>@item.NameAccount</td>
            <td>@item.Content</td>
            <td>@item.Day</td>
            <td>@item.ProductId</td>
            <td>@item.Note</td>



            <td>
                <a href="@Url.Action("Edit","CommentAdmin",new { id= @item.Id})"><img src="~/Content/images/done.jpg" /></a>

            </td>
        </tr>

    }
</table>