StoreLaptopApp/Areas/admin/Controllers/ProductAdminController.cs
using DoAnChuyenNganhConnection;
using StoreLaptopApp.Models.Bus;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StoreLaptopApp.Areas.admin.Controllers
{
    public class ProductAdminController : Controller
    {
        [Authorize(Roles = "Admin")]
        // GET: admin/Product
        public ActionResult Index()
        {
            var ds= ShopLaptopBus.DanhSachAdmin();
            return View(ds);
        }

        // GET: admin/Product/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: admin/Product/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: admin/Product/Create
        [HttpPost]
        public ActionResult Create(Product product)
        {
            try
            {
                // TODO: Add insert logic here
                ShopLaptopBus.Them(product);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: admin/Product/Edit/5
        public ActionResult Edit(int id)
        {
            return View(ShopLaptopBus.ChiTietAdmin(id));
        }

        // POST: admin/Product/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Product product)
        {
            try
            {
                // TODO: Add update logic here
                ShopLaptopBus.Update(id, product);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: admin/Product/Delete/5
        public ActionResult Delete(int id)
        {
            return View(ShopLaptopBus.ChiTietAdmin(id));
        }

        // POST: admin/Product/Delete/5
        [HttpPost]
        public ActionResult Delete( Product product)
        {
            try
            {
                // TODO: Add delete logic here
                ShopLaptopBus.DeleteSp( product);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

StoreLaptopApp/Areas/admin/Views/ProductAdmin/Create.cshtml
@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
}
<script src="~/Areas/Aset/js/product/previewFile.js"></script>

<style>
    input[type=text] {
        width: 100%;
        padding: 12px 20px;
        margin: 8px 0;
        display: inline-block;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
    }

    input[type=submit] {
        width: 100%;
        background-color: #4CAF50;
        color: white;
        padding: 14px 20px;
        margin: 8px 0;
        border: none;
        border-radius: 4px;
        cursor: pointer;
    }

        input[type=submit]:hover {
            background-color: #45a049;
        }

    /*div {
        border-radius: 5px;
        background-color: #f2f2f2;
        padding: 20px;
        margin: auto;
    }*/
</style>

<div style=" padding: 20px;">
    @using (Html.BeginForm("Create", "ProductAdmin", FormMethod.Post, new
    {
        //enctype = "multipart/form-data"



    }))
    {
        <label for="fname" style="margin-left:-459px">Chon Hinh Chinh</label>
        <input type="File" id="file_Cover" name="Cover" onchange="previewFile();" style="float:left; margin-left:165px">
        <div>
            <img id="target" class="img" src="#" alt="image" style="float:right; width:262px; height:201px" />
        </div>
        <br />

        <label for="fname" style="margin-left:-459px">Chon Hinh 1</label>
        <input type="File" id="file_Cover" name="Cover1" onchange="previewFile();" style="float:left; margin-left:165px">
        <div>
            <br  style="float:right; width:262px; height:201px" />
        </div>

        <label for="fname" style="margin-left:-459px">Chon Hinh 2</label>
        <input type="File" id="file_Cover" name="Cover2" onchange="previewFile();" style="float:left; margin-left:165px">
        <div>
            <br  style="float:right; width:2px; height:201px" />
        </div>

        <label for="fname" style="margin-left:-459px">Chon Hinh 3</label>
        <input type="File" id="file_Cover" name="Cover3" onchange="previewFile();" style="float:left; margin-left:165px">
        <div>
            <br style="float:right; width:1px; height:201px" />
        </div>

        <label for="fname" style="margin-left:-459px">Chon Hinh 4</label>
        <input type="File" id="file_Cover" name="Cover4" onchange="previewFile();" style="float:left; margin-left:165px">
        <div>
            <br style="float:right; width:1px; height:201px" />
        </div>


        <label for="fname" style="margin-top:245px">Mã sản phẩm</label>
        <input type="text" id="fname" name="Id" placeholder="Nhập mã sản phẩm" required>

        <label for="lname">Tên sản phẩm</label>
        <input type="text" id="lname" name="Name" placeholder="Nhập tên sản phẩm" required>

        <label for="fname">Miêu tả sản phẩm</label>
        <input type="text" id="fname" name="Description" placeholder="" required>

        <label for="lname">Năm</label>
        <input type="text" id="lname" name="PublicYear" placeholder="Nhập năm sản phẩm" required>

        <label for="lname">Gía</label>
        <input type="text" id="lname" name="Price" placeholder="" required>

        <label for="country">Nhập loại sản phẩm</label>
        <select id="country" name="IdProductType" style="width:89px;height:26px;" required>
            <option value="5">Cao cấp</option>
            <option value="6">Trung bình</option>
            <option value="7">Thấp</option>

        </select>
        <label for="country">Nhập tên nhà sản xuất</label>
        <select id="country" name="IdProducer" style="width:89px;height:26px;" required>
            <option value="1">DELL</option>
            <option value="2">ASUS</option>
            <option value="3">ACER</option>
            <option value="4">MACBOOK</option>
            <option value="5">Tai nghe</option>
            <option value="6">Sạc</option>
            <option value="7">Bàn phím</option>

        </select>

        <label for="country">Top6Product</label>
        <select id="country" name="Note" style="width:89px;height:26px;" required>
            <option value="1">Yes</option>
            <option value="0">No</option>


        </select>
        <label for="country">Top phụ kiện</label>
        <select id="country" name="Note" style="width:89px;height:26px;" required>
            <option value="5">Sạc #1</option>
            <option value="6">Sạc #2</option>
            <option value="7">Tai nghe #1</option>
            <option value="8">Tai nghe #2</option>
            <option value="9">Bàn phím #1</option>
            <option value="10">Bàn phím #2</option>
            <option value="0">No</option>

        </select>

        <input type="submit" value="Submit">
    }
</div>

StoreLaptopApp/Areas/admin/Views/ProductAdmin/Delete.cshtml
@model DoAnChuyenNganhConnection.Product
@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
}
<style>
    input[type=text] {
        width: 100%;
        padding: 12px 20px;
        margin: 8px 0;
        display: inline-block;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
    }

    input[type=submit] {
        width: 100%;
        background-color: #4CAF50;
        color: white;
        padding: 14px 20px;
        margin: 8px 0;
        border: none;
        border-radius: 4px;
        cursor: pointer;
    }

        input[type=submit]:hover {
            background-color: #45a049;
        }

    /*div {
        border-radius: 5px;
        background-color: #f2f2f2;
        padding: 20px;
        margin: auto;
    }*/
</style>

<div style=" padding: 20px;">
    @using (Html.BeginForm("Delete", "ProductAdmin", FormMethod.Post, new
    {

    }))
    {

        <label for="fname">Mã sản phẩm</label>
        <input type="text" id="fname" name="Id" placeholder="" required value="@Model.Id">

        <label for="lname">Tên sản phẩm</label>
        <input type="text" id="lname" name="Name" placeholder="" required value="@Model.Name">

        <label for="country">Miêu tả sản phẩm</label>
        <input type="text" id="lname" name="Description" placeholder="" required value="@Model.Description">

        <label for="country">Năm sản xuất</label>
        <input type="text" id="lname" name="PublicYear" placeholder="" required value="@Model.PublicYear">

        <label for="country">Gía</label>
        <input type="text" id="lname" name="Price" placeholder="" required value="@Model.Price">

        <label for="country">Hình</label>
        <input type="text" id="lname" name="Cover" placeholder="" required value="@Model.Cover">

        <label for="country">Hình1</label>
        <input type="text" id="lname" name="Cover1" placeholder="" required value="@Model.Cover1">

        <label for="country">Hình2</label>
        <input type="text" id="lname" name="Cover2" placeholder="" required value="@Model.Cover2">

        <label for="country">Hình3</label>
        <input type="text" id="lname" name="Cover3" placeholder="" required value="@Model.Cover3">

        <label for="country">Hình4</label>
        <input type="text" id="lname" name="Cover4" placeholder="" required value="@Model.Cover4">

        <label for="country">Loại sản phẩm</label>
        <input type="text" id="lname" name="IdProductType" placeholder="" required value="@Model.IdProductType">

        <label for="country">Nhà sản xuất</label>
        <input type="text" id="lname" name="IdProducer" placeholder="" required value="@Model.IdProducer">
        <label for="country">Ghi chú</label>
        <input type="text" id="lname" name="Note" placeholder="" required value="@Model.Note">


        <input type="submit" value="Submit">
    }
</div>

StoreLaptopApp/Areas/admin/Views/ProductAdmin/Edit.cshtml
@model DoAnChuyenNganhConnection.Product
@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
}
<script src="~/Areas/Aset/js/product/previewFile.js"></script>

<style>
    input[type=text] {
        width: 100%;
        padding: 12px 20px;
        margin: 8px 0;
        display: inline-block;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
    }

    input[type=submit] {
        width: 100%;
        background-color: #4CAF50;
        color: white;
        padding: 14px 20px;
        margin: 8px 0;
        border: none;
        border-radius: 4px;
        cursor: pointer;
    }

        input[type=submit]:hover {
            background-color: #45a049;
        }

    /*div {
        border-radius: 5px;
        background-color: #f2f2f2;
        
        margin: auto;
    }*/
</style>

<div style="padding: 20px;">
    @using (Html.BeginForm("Edit", "ProductAdmin", FormMethod.Post, new
    {

    }))
    {

        <label for="fname" style="margin-left:-459px">Chon Hinh</label>
        <input type="File" id="file_Cover" name="Cover" onchange="previewFile();" style="float:left; margin-left:165px">
        <div>
            <img id="target" class="img" src="~/Content/images/@Model.Cover" alt="image" style="float:right; width:262px; height:201px" />
        </div>

        <br />

        <label for="fname" style="margin-left:-459px">Chon Hinh 1</label>
        <input type="File" id="file_Cover" name="Cover1" onchange="previewFile();" style="float:left; margin-left:165px">
        <div>
            <br style="float:right; width:262px; height:201px" />
        </div>

        <label for="fname" style="margin-left:-459px">Chon Hinh 2</label>
        <input type="File" id="file_Cover" name="Cover2" onchange="previewFile();" style="float:left; margin-left:165px">
        <div>
            <br style="float:right; width:2px; height:201px" />
        </div>

        <label for="fname" style="margin-left:-459px">Chon Hinh 3</label>
        <input type="File" id="file_Cover" name="Cover3" onchange="previewFile();" style="float:left; margin-left:165px">
        <div>
            <br style="float:right; width:1px; height:201px" />
        </div>

        <label for="fname" style="margin-left:-459px">Chon Hinh 4</label>
        <input type="File" id="file_Cover" name="Cover4" onchange="previewFile();" style="float:left; margin-left:165px">
        <div>
            <br style="float:right; width:1px; height:201px" />
        </div>


        <label for="fname" style="margin-top:245px">Mã sản phẩm</label>
        <input type="text" id="fname" name="Id" placeholder="Nhập mã sản phẩm" required value="@Model.Id">

        <label for="lname">Tên sản phẩm</label>
        <input type="text" id="lname" name="Name" placeholder="Nhập tên sản phẩm" required value="@Model.Name">
        <label for="lname">Miêu tả sản phẩm</label>
        <input type="text" id="lname" name="Description" placeholder="" required value="@Model.Description">
        <label for="lname">Năm</label>
        <input type="text" id="lname" name="PublicYear" placeholder="Nhập năm sản phẩm" required value="@Model.PublicYear">
        <label for="lname">Gía</label>
        <input type="text" id="lname" name="Price" placeholder="" required value="@Model.Price">

        <label for="country">Nhập loại sản phẩm</label>
        <select id="country" name="IdProductType" style="width:89px;height:26px;" required value="@Model.IdProductType">
            <option value="5">Cao cấp</option>
            <option value="6">Trung bình</option>
            <option value="7">Thấp</option>

        </select>
        <label for="country">Nhập tên nhà sản xuất</label>
        <select id="country" name="IdProducer" style="width:89px;height:26px;" required value="@Model.IdProducer">
            <option value="1">DELL</option>
            <option value="2">ASUS</option>
            <option value="3">ACER</option>
            <option value="4">MACBOOK</option>
            <option value="5">Tai nghe</option>
            <option value="6">Sạc</option>
            <option value="7">Bàn phím</option>

        </select>

        <label for="country">Top6Product</label>
        <select id="country" name="Note" style="width:89px;height:26px;" required value="@Model.Note">
            <option value="1">Yes</option>
            <option value="0">No</option>


        </select>
        <label for="country">Top phụ kiện</label>
        <select id="country" name="Note" style="width:89px;height:26px;" required value="@Model.Note">
            <option value="5">Sạc #1</option>
            <option value="6">Sạc #2</option>
            <option value="7">Tai nghe #1</option>
            <option value="8">Tai nghe #2</option>
            <option value="9">Bàn phím #1</option>
            <option value="10">Bàn phím #2</option>
            <option value="0">No</option>

        </select>

        <input type="submit" value="Submit">
    }
</div>

StoreLaptopApp/Areas/admin/Views/ProductAdmin/Index.cshtml
@model IEnumerable<DoAnChuyenNganhConnection.Product>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
}


<style>
    table {
        border-collapse: collapse;
        width: 100%;
        margin: auto;
    }

    th, td {
        text-align: center;
        padding: 8px;
    }

    tr:nth-child(even) {
        background-color: #f2f2f2
    }

    th {
        background-color: #04AA6D;
        color: white;
    }
</style>



<table>
    <tr>
        <th>Mã sản phẩm</th>
        <th>Tên sản phẩm</th>
        <th>Miêu tả sản phẩm</th>
        <th>Năm sản xuất</th>
        <th>Gía</th>
        <th>Hình</th>
        <th>Hình1</th>
        <th>Hình2</th>
        <th>Hình3</th>
        <th>Hình4</th>
        <th>Loại sản phẩm</th>
        <th>Nhà sản xuất</th>
        <th>Ghi chú</th>
        <th colspan="2">
            <a href="@Url.Action("Create","ProductAdmin")"><img src="~/Content/images/add.png" /></a>
        </th>
    </tr>
    @foreach (var item in Model)
    {

        <tr>
            <td>@item.Id</td>
            <td>@item.Name</td>
            <td>@item.Description</td>
            <td>@item.PublicYear</td>
            <td>@item.Price</td>
            <td><img src="~/Content/images/@item.Cover" style="width:100px; height:70px" /></td>
            <td><img src="~/Content/images/@item.Cover1" style="width:100px; height:70px" /></td>
            <td><img src="~/Content/images/@item.Cover2" style="width:100px; height:70px" /></td>
            <td><img src="~/Content/images/@item.Cover3" style="width:100px; height:70px" /></td>
            <td><img src="~/Content/images/@item.Cover4" style="width:100px; height:70px" /></td>
            <td>@item.IdProductType</td>
            <td>@item.IdProducer</td>
            <td>@item.Note</td>

            <td>
                <a href="@Url.Action("Edit","ProductAdmin",new { id= @item.Id})"><img src="~/Content/images/edit.png" /></a>
            </td>
            <td>
                <a href="@Url.Action("Delete","ProductAdmin",new { id= @item.Id})"><img src="~/Content/images/delete.png" /></a>
            </td>
        </tr>

    }
</table>